# Generated by Django 4.0 on 2023-11-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attribute', '0003_attribute_filter_type_attribute_is_filter'),
        ('ads', '0007_ads_is_vip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ads',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ads_images'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='attributes',
            field=models.ManyToManyField(blank=True, to='attribute.Attribute'),
        ),
    ]
