# Generated by Django 4.0 on 2023-11-20 07:28

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0008_alter_ads_image_alter_subcategory_attributes'),
    ]

    operations = [
        pgtrigger.migrations.AddTrigger(
            model_name='ads',
            trigger=pgtrigger.compiler.Trigger(name='address_set', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                NEW.address = (SELECT CONCAT(common_region.title ,', ', common_district.title) FROM common_district JOIN common_region ON common_district.region_id=common_region.id WHERE common_district.id=NEW.district_id);RETURN NEW; \n\n           \n            ", hash='a6647642f5193030185828b31f8f5185580a728f', operation='UPDATE OR INSERT', pgid='pgtrigger_address_set_65888', table='ads_ads', when='BEFORE')),
        ),
    ]
