# Generated by Django 4.0 on 2023-11-20 13:24

from django.db import migrations
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0010_remove_ads_address_set_ads_address_set'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='ads',
            name='address_set',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='ads',
            trigger=pgtrigger.compiler.Trigger(name='address_set', sql=pgtrigger.compiler.UpsertTriggerSql(func="\n                    NEW.address = (SELECT CONCAT(common_region.title, ', ', common_district.title) FROM common_district JOIN common_region ON common_district.region_id=common_region.id WHERE common_district.id=NEW.district_id);RETURN NEW; \n                ", hash='4e0dbb65dbe959f95298f4f69b86cdffec7456ec', operation='UPDATE OR INSERT', pgid='pgtrigger_address_set_65888', table='ads_ads', when='BEFORE')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='category',
            trigger=pgtrigger.compiler.Trigger(name='ads_count_update', sql=pgtrigger.compiler.UpsertTriggerSql(func='\n                    NEW.ads_count = (\n                            SELECT COUNT(*) FROM ads_ads\n                        );\n                    RETURN NEW; \n                ', hash='6ad3a007b4a2d8516f368948ae765f9c53de020f', operation='DELETE OR UPDATE OR INSERT', pgid='pgtrigger_ads_count_update_ec684', table='ads_category', when='BEFORE')),
        ),
    ]
