# Generated by Django 3.2.23 on 2023-11-30 03:41

from django.db import migrations, models
import pgtrigger.migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0011_remove_ads_address_set_ads_address_set_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ads',
            options={'ordering': ('id',), 'verbose_name_plural': 'Ads'},
        ),
        migrations.AlterModelOptions(
            name='adsattributevalue',
            options={'verbose_name_plural': 'Ads Attribute Value'},
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='ads',
            name='address_set',
        ),
        migrations.AddField(
            model_name='ads',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ads',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
