# Generated by Django 3.2.23 on 2023-11-30 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0012_auto_20231130_0341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ads',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='content_uz',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='ads',
            name='title_uz',
        ),
    ]
