# Generated by Django 3.2.23 on 2023-11-30 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0013_auto_20231130_0415'),
    ]

    operations = [
        migrations.AddField(
            model_name='ads',
            name='language',
            field=models.CharField(choices=[('UZ', 'Uz'), ('EN', 'En'), ('RU', 'Ru')], default='UZ', max_length=10),
        ),
    ]
